# Generated by Django 6.0.4 on 2026-04-30 14:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('control_type', models.CharField(choices=[('security_rule', 'Security Rule'), ('config', 'Configuration')], default='security_rule', max_length=32)),
                ('description', models.TextField()),
                ('rationale', models.TextField(blank=True)),
                ('audit', models.TextField(blank=True)),
                ('remediation', models.TextField(blank=True)),
                ('default_severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=32)),
                ('implementation_version', models.CharField(default='v1', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['control_id'],
            },
        ),
        migrations.CreateModel(
            name='SecurityRuleSearchState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('query_text', models.TextField(blank=True)),
                ('canonical_query', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('canonical_query', models.JSONField(default=dict)),
                ('is_baseline', models.BooleanField(default=False)),
                ('adjusted_severity', models.CharField(blank=True, choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='assessments.control')),
            ],
            options={
                'ordering': ['control__control_id', '-is_baseline', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RuleFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_findings', to='assessments.assessmentrun')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_findings', to='assessments.control')),
                ('security_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_findings', to='integrations.securityrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finding_links', to='assessments.controlquery')),
                ('rule_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.rulefinding')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='rulefinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='rule_findings', through='assessments.RuleFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.AddConstraint(
            model_name='rulefindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('rule_finding', 'control_query'), name='unique_rule_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='rulefinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_9200ce_idx'),
        ),
        migrations.AddIndex(
            model_name='rulefinding',
            index=models.Index(fields=['security_rule'], name='assessments_securit_1185a6_idx'),
        ),
        migrations.AddIndex(
            model_name='rulefinding',
            index=models.Index(fields=['status'], name='assessments_status_3b098a_idx'),
        ),
        migrations.AddIndex(
            model_name='rulefinding',
            index=models.Index(fields=['severity'], name='assessments_severit_dab7f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='rulefinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'security_rule'), name='unique_rule_finding_per_run_control_rule'),
        ),
    ]
