# Generated by Django 6.0.4 on 2026-05-01 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('integrations', '0003_managementplaneprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_type',
            field=models.CharField(choices=[('security_rule', 'Security Rule'), ('config', 'Configuration'), ('management_plane', 'Management Plane')], default='security_rule', max_length=32),
        ),
        migrations.CreateModel(
            name='ManagementPlaneFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_plane_findings', to='assessments.assessmentrun')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='management_plane_findings', to='assessments.control')),
                ('management_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.managementplaneprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagementPlaneFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_finding_links', to='assessments.controlquery')),
                ('management_plane_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.managementplanefinding')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='managementplanefinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='management_plane_findings', through='assessments.ManagementPlaneFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.AddConstraint(
            model_name='managementplanefindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('management_plane_finding', 'control_query'), name='unique_management_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='managementplanefinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_62a328_idx'),
        ),
        migrations.AddIndex(
            model_name='managementplanefinding',
            index=models.Index(fields=['management_profile'], name='assessments_managem_793b37_idx'),
        ),
        migrations.AddIndex(
            model_name='managementplanefinding',
            index=models.Index(fields=['status'], name='assessments_status_190dab_idx'),
        ),
        migrations.AddIndex(
            model_name='managementplanefinding',
            index=models.Index(fields=['severity'], name='assessments_severit_eb065a_idx'),
        ),
        migrations.AddConstraint(
            model_name='managementplanefinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'management_profile'), name='unique_management_finding_per_run_control_profile'),
        ),
    ]
