# Generated by Django 6.0.5 on 2026-05-15 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_control_control_type_managementplanefinding_and_more'),
        ('integrations', '0005_client_engagementenvironment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(blank=True, max_length=128, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('version', models.CharField(default='v1', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('is_seeded', models.BooleanField(default=False)),
                ('is_snapshot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['is_snapshot', '-is_seeded', 'label', 'version', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEnvironmentCatalogState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_environment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_catalog_state', to='integrations.applicationenvironment')),
                ('current_catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environment_states', to='assessments.catalog')),
            ],
            options={
                'ordering': ['application_environment_id'],
            },
        ),
    ]
