from django.urls import path

from assessments.plain_language.views import PlainLanguageSecurityRuleQueryView
from assessments.views import (
    ControlCreateView,
    ControlDeleteView,
    ControlDetailView,
    ControlListView,
    ControlQueryCreateView,
    ControlQueryDeleteView,
    ControlQueryUpdateView,
    ControlRunFindingsView,
    ControlRunManagementFindingsView,
    ControlUpdateView,
    ManagementPlaneFindingListView,
    RuleFindingDocxDownloadView,
    RuleFindingListView,
    RuleFindingXlsxDownloadView,
    SecurityRuleListView,
)


urlpatterns = [
    path(
        "controls/",
        ControlListView.as_view(),
        name="assessment_control_list",
    ),
    path(
        "controls/create/",
        ControlCreateView.as_view(),
        name="assessment_control_create",
    ),
    path(
        "controls/run-findings/",
        ControlRunFindingsView.as_view(),
        name="assessment_control_run_findings",
    ),
    path(
        "controls/run-management-findings/",
        ControlRunManagementFindingsView.as_view(),
        name="assessment_control_run_management_findings",
    ),
    path(
        "findings/",
        RuleFindingListView.as_view(),
        name="assessment_rule_finding_list",
    ),
    path(
        "findings/report.docx",
        RuleFindingDocxDownloadView.as_view(),
        name="assessment_rule_finding_docx_download",
    ),
    path(
        "findings/report.xlsx",
        RuleFindingXlsxDownloadView.as_view(),
        name="assessment_rule_finding_xlsx_download",
    ),
    path(
        "management-findings/",
        ManagementPlaneFindingListView.as_view(),
        name="assessment_management_finding_list",
    ),
    path(
        "controls/<int:pk>/",
        ControlDetailView.as_view(),
        name="assessment_control_detail",
    ),
    path(
        "control-queries/create/",
        ControlQueryCreateView.as_view(),
        name="assessment_control_query_create",
    ),
    path(
        "controls/<int:pk>/edit/",
        ControlUpdateView.as_view(),
        name="assessment_control_update",
    ),
    path(
        "controls/<int:pk>/queries/<int:query_pk>/edit/",
        ControlQueryUpdateView.as_view(),
        name="assessment_control_query_update",
    ),
    path(
        "controls/<int:pk>/queries/<int:query_pk>/delete/",
        ControlQueryDeleteView.as_view(),
        name="assessment_control_query_delete",
    ),
    path(
        "controls/<int:pk>/delete/",
        ControlDeleteView.as_view(),
        name="assessment_control_delete",
    ),
    path(
        "security-rules/",
        SecurityRuleListView.as_view(),
        name="assessment_security_rule_list",
    ),
    path(
        "security-rules/plain-language/",
        PlainLanguageSecurityRuleQueryView.as_view(),
        name="assessment_security_rule_plain_language",
    ),
]
