from django.urls import path

from assessments.catalog_views import (
    CatalogApplyView,
    CatalogCreateFromCurrentControlsView,
    CatalogDownloadView,
    CatalogListView,
    CatalogRefreshSeedView,
    CatalogSeedDownloadView,
)
from assessments.plain_language.views import PlainLanguageSecurityRuleQueryView
from assessments.views import (
    ControlCreateView,
    SystemView,
    ControlDeleteView,
    ControlDetailView,
    ControlListView,
    ControlQueryCreateView,
    ControlQueryDeleteView,
    ControlQueryUpdateView,
    ControlRunFindingsView,
    ControlRunConfigurationFindingsView,
    ControlUpdateView,
    DeviceConfigurationProfileListView,
    InterfaceManagementProfileListView,
    LoginBannerListView,
    CertificateListView,
    CertificateProfileListView,
    ManagementTlsListView,
    MasterKeyListView,
    PasswordComplexityListView,
    SslTlsServiceProfileListView,
    ManagementInterfaceListView,
    FindingListView,
    RuleFindingDocxDownloadView,
    RuleFindingXlsxDownloadView,
    SecurityRuleListView,
)


urlpatterns = [
    path(
        "catalogs/",
        CatalogListView.as_view(),
        name="assessment_catalog_list",
    ),
    path(
        "catalogs/export-seed/",
        CatalogSeedDownloadView.as_view(),
        name="assessment_catalog_seed_download",
    ),
    path(
        "catalogs/create-from-current/",
        CatalogCreateFromCurrentControlsView.as_view(),
        name="assessment_catalog_create_from_current",
    ),
    path(
        "catalogs/refresh-seed/",
        CatalogRefreshSeedView.as_view(),
        name="assessment_catalog_refresh_seed",
    ),
    path(
        "catalogs/<int:pk>/apply/",
        CatalogApplyView.as_view(),
        name="assessment_catalog_apply",
    ),
    path(
        "catalogs/<int:pk>/download/",
        CatalogDownloadView.as_view(),
        name="assessment_catalog_download",
    ),
    path(
        "controls/",
        ControlListView.as_view(),
        name="assessment_control_list",
    ),
    path(
        "controls/create/",
        ControlCreateView.as_view(),
        name="assessment_control_create",
    ),
    path(
        "controls/run-findings/",
        ControlRunFindingsView.as_view(),
        name="assessment_control_run_findings",
    ),
    path(
        "controls/run-configuration-findings/",
        ControlRunConfigurationFindingsView.as_view(),
        name="assessment_control_run_configuration_findings",
    ),
    path(
        "findings/",
        FindingListView.as_view(),
        name="assessment_finding_list",
    ),
    path(
        "findings/report.docx",
        RuleFindingDocxDownloadView.as_view(),
        name="assessment_rule_finding_docx_download",
    ),
    path(
        "findings/report.xlsx",
        RuleFindingXlsxDownloadView.as_view(),
        name="assessment_rule_finding_xlsx_download",
    ),
    path(
        "system/",
        SystemView.as_view(),
        name="assessment_system",
    ),
    path(
        "management-interfaces/",
        ManagementInterfaceListView.as_view(),
        name="assessment_management_interface_list",
    ),
    path(
        "interface-management-profiles/",
        InterfaceManagementProfileListView.as_view(),
        name="assessment_interface_management_profile_list",
    ),
    path(
        "login-banner/",
        LoginBannerListView.as_view(),
        name="assessment_login_banner_list",
    ),
    path(
        "management-tls/",
        ManagementTlsListView.as_view(),
        name="assessment_management_tls_list",
    ),
    path(
        "ssl-tls-profiles/",
        SslTlsServiceProfileListView.as_view(),
        name="assessment_ssl_tls_service_profile_list",
    ),
    path(
        "certificates/",
        CertificateListView.as_view(),
        name="assessment_certificate_list",
    ),
    path(
        "certificate-profiles/",
        CertificateProfileListView.as_view(),
        name="assessment_certificate_profile_list",
    ),
    path(
        "master-key/",
        MasterKeyListView.as_view(),
        name="assessment_master_key_list",
    ),
    path(
        "password-complexity/",
        PasswordComplexityListView.as_view(),
        name="assessment_password_complexity_list",
    ),
    path(
        "device-configuration/",
        DeviceConfigurationProfileListView.as_view(),
        name="assessment_device_configuration_profile_list",
    ),
    path(
        "controls/<int:pk>/",
        ControlDetailView.as_view(),
        name="assessment_control_detail",
    ),
    path(
        "control-queries/create/",
        ControlQueryCreateView.as_view(),
        name="assessment_control_query_create",
    ),
    path(
        "controls/<int:pk>/edit/",
        ControlUpdateView.as_view(),
        name="assessment_control_update",
    ),
    path(
        "controls/<int:pk>/queries/<int:query_pk>/edit/",
        ControlQueryUpdateView.as_view(),
        name="assessment_control_query_update",
    ),
    path(
        "controls/<int:pk>/queries/<int:query_pk>/delete/",
        ControlQueryDeleteView.as_view(),
        name="assessment_control_query_delete",
    ),
    path(
        "controls/<int:pk>/delete/",
        ControlDeleteView.as_view(),
        name="assessment_control_delete",
    ),
    path(
        "security-rules/",
        SecurityRuleListView.as_view(),
        name="assessment_security_rule_list",
    ),
    path(
        "security-rules/plain-language/",
        PlainLanguageSecurityRuleQueryView.as_view(),
        name="assessment_security_rule_plain_language",
    ),
]
