# Generated by Django 6.0.6 on 2026-06-22 20:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(blank=True, max_length=128, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('version', models.CharField(default='v1', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('is_seeded', models.BooleanField(default=False)),
                ('is_snapshot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['is_snapshot', '-is_seeded', 'label', 'version', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('control_type', models.CharField(choices=[('security_rule', 'Security Rule'), ('config', 'Configuration'), ('device_configuration', 'Device Configuration')], default='security_rule', max_length=32)),
                ('description', models.TextField()),
                ('rationale', models.TextField(blank=True)),
                ('audit', models.TextField(blank=True)),
                ('remediation', models.TextField(blank=True)),
                ('default_severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=32)),
                ('implementation_version', models.CharField(default='v1', max_length=64)),
                ('target_model', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['control_id'],
            },
        ),
        migrations.CreateModel(
            name='SecurityRuleSearchState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('query_text', models.TextField(blank=True)),
                ('canonical_query', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEnvironmentCatalogState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_environment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_catalog_state', to='integrations.applicationenvironment')),
                ('current_catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environment_states', to='assessments.catalog')),
            ],
            options={
                'ordering': ['application_environment_id'],
            },
        ),
        migrations.CreateModel(
            name='ControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('canonical_query', models.JSONField(default=dict)),
                ('is_baseline', models.BooleanField(default=False)),
                ('adjusted_severity', models.CharField(blank=True, choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='assessments.control')),
            ],
            options={
                'ordering': ['control__control_id', '-is_baseline', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceConfigurationFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_configuration_findings', to='assessments.assessmentrun')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_configuration_findings', to='assessments.control')),
                ('device_configuration_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.deviceconfigurationprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceConfigurationFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_configuration_finding_links', to='assessments.controlquery')),
                ('device_configuration_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.deviceconfigurationfinding')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='deviceconfigurationfinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='device_configuration_findings', through='assessments.DeviceConfigurationFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.CreateModel(
            name='RuleFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_findings', to='assessments.assessmentrun')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_findings', to='assessments.control')),
                ('security_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_findings', to='integrations.securityrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finding_links', to='assessments.controlquery')),
                ('rule_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.rulefinding')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='rulefinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='rule_findings', through='assessments.RuleFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.AddConstraint(
            model_name='deviceconfigurationfindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('device_configuration_finding', 'control_query'), name='unique_device_configuration_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='deviceconfigurationfinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_994852_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceconfigurationfinding',
            index=models.Index(fields=['device_configuration_profile'], name='assessments_device__4b9fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceconfigurationfinding',
            index=models.Index(fields=['status'], name='assessments_status_d0d1bd_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceconfigurationfinding',
            index=models.Index(fields=['severity'], name='assessments_severit_affca0_idx'),
        ),
        migrations.AddConstraint(
            model_name='deviceconfigurationfinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'device_configuration_profile'), name='unique_device_configuration_finding_per_run_control_profile'),
        ),
        migrations.AddConstraint(
            model_name='rulefindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('rule_finding', 'control_query'), name='unique_rule_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='rulefinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_9200ce_idx'),
        ),
        migrations.AddIndex(
            model_name='rulefinding',
            index=models.Index(fields=['security_rule'], name='assessments_securit_1185a6_idx'),
        ),
        migrations.AddIndex(
            model_name='rulefinding',
            index=models.Index(fields=['status'], name='assessments_status_3b098a_idx'),
        ),
        migrations.AddIndex(
            model_name='rulefinding',
            index=models.Index(fields=['severity'], name='assessments_severit_dab7f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='rulefinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'security_rule'), name='unique_rule_finding_per_run_control_rule'),
        ),
    ]
