# Generated by Django 6.0.5 on 2026-07-06 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('optivedge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationenvironmentcatalogstate',
            name='application_environment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_catalog_state', to='optivedge.applicationenvironment'),
        ),
    ]
