# Generated by Django 6.0.5 on 2026-08-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_applicationenvironmentcatalogstate_application_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulefinding',
            name='matched_query_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
