# Generated by Django 6.0.6 on 2026-06-22 18:01

from django.db import migrations, models


_CONTROL_TYPE_TARGET_MODEL = {
    "security_rule": "integrations.SecurityRule",
    "management_plane": "integrations.ManagementPlaneProfile",
}


def populate_target_model(apps, schema_editor):
    Control = apps.get_model("assessments", "Control")
    for control in Control.objects.all():
        control.target_model = _CONTROL_TYPE_TARGET_MODEL.get(control.control_type, "")
        control.save(update_fields=["target_model"])


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_catalog_applicationenvironmentcatalogstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='target_model',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.RunPython(populate_target_model, migrations.RunPython.noop),
    ]
