# Generated by Django 6.0.5 on 2026-08-28 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_rulefinding_matched_query_names'),
        ('integrations', '0019_managementinterface_permittedsource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_type',
            field=models.CharField(choices=[('security_rule', 'Security Rule'), ('config', 'Configuration'), ('device_configuration', 'Device Configuration'), ('management_interface', 'Management Interface')], default='security_rule', max_length=32),
        ),
        migrations.CreateModel(
            name='ManagementInterfaceFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('matched_query_names', models.JSONField(blank=True, default=list)),
                ('subject_name', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_interface_findings', to='assessments.assessmentrun')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='management_interface_findings', to='assessments.control')),
                ('management_interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.managementinterface')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagementInterfaceFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_interface_finding_links', to='assessments.controlquery')),
                ('management_interface_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.managementinterfacefinding')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='managementinterfacefinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='management_interface_findings', through='assessments.ManagementInterfaceFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.AddConstraint(
            model_name='managementinterfacefindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('management_interface_finding', 'control_query'), name='unique_management_interface_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='managementinterfacefinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_2d1125_idx'),
        ),
        migrations.AddIndex(
            model_name='managementinterfacefinding',
            index=models.Index(fields=['management_interface'], name='assessments_managem_da4fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='managementinterfacefinding',
            index=models.Index(fields=['status'], name='assessments_status_527634_idx'),
        ),
        migrations.AddIndex(
            model_name='managementinterfacefinding',
            index=models.Index(fields=['severity'], name='assessments_severit_d13b69_idx'),
        ),
        migrations.AddConstraint(
            model_name='managementinterfacefinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'management_interface'), name='unique_management_interface_finding_per_run_control_surface'),
        ),
    ]
