# Generated by Django 6.0.5 on 2026-08-31 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_control_control_type_and_more'),
        ('integrations', '0025_interfacemanagementprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_type',
            field=models.CharField(choices=[('security_rule', 'Security Rule'), ('config', 'Configuration'), ('device_configuration', 'Device Configuration'), ('management_interface', 'Management Interface'), ('interface_management_profile', 'Interface Management Profile')], default='security_rule', max_length=32),
        ),
        migrations.CreateModel(
            name='InterfaceManagementProfileFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('matched_query_names', models.JSONField(blank=True, default=list)),
                ('subject_name', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_management_profile_findings', to='assessments.assessmentrun')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interface_management_profile_findings', to='assessments.control')),
                ('interface_management_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.interfacemanagementprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterfaceManagementProfileFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_management_profile_finding_links', to='assessments.controlquery')),
                ('interface_management_profile_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.interfacemanagementprofilefinding')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='interfacemanagementprofilefinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='interface_management_profile_findings', through='assessments.InterfaceManagementProfileFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.AddConstraint(
            model_name='interfacemanagementprofilefindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('interface_management_profile_finding', 'control_query'), name='unique_imp_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='interfacemanagementprofilefinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_6faa7b_idx'),
        ),
        migrations.AddIndex(
            model_name='interfacemanagementprofilefinding',
            index=models.Index(fields=['interface_management_profile'], name='assessments_interfa_dc2533_idx'),
        ),
        migrations.AddIndex(
            model_name='interfacemanagementprofilefinding',
            index=models.Index(fields=['status'], name='assessments_status_29d89a_idx'),
        ),
        migrations.AddIndex(
            model_name='interfacemanagementprofilefinding',
            index=models.Index(fields=['severity'], name='assessments_severit_315f8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='interfacemanagementprofilefinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'interface_management_profile'), name='unique_imp_finding_per_run_control_profile'),
        ),
    ]
