# Generated by Django 6.0.8 on 2026-09-02 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_control_control_type_and_more'),
        ('integrations', '0033_certificateprofile_ssltlsserviceprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_type',
            field=models.CharField(choices=[('security_rule', 'Security Rule'), ('config', 'Configuration'), ('device_configuration', 'Device Configuration'), ('management_interface', 'Management Interface'), ('interface_management_profile', 'Interface Management Profile'), ('ssl_tls_service_profile', 'SSL/TLS Service Profile'), ('certificate_profile', 'Certificate Profile')], default='security_rule', max_length=32),
        ),
        migrations.CreateModel(
            name='CertificateProfileFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('matched_query_names', models.JSONField(blank=True, default=list)),
                ('subject_name', models.CharField(blank=True, max_length=64)),
                ('subject_scope', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_profile_findings', to='assessments.assessmentrun')),
                ('certificate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.certificateprofile')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_profile_findings', to='assessments.control')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateProfileFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_profile_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.certificateprofilefinding')),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_profile_finding_links', to='assessments.controlquery')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='certificateprofilefinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='certificate_profile_findings', through='assessments.CertificateProfileFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.CreateModel(
            name='SslTlsServiceProfileFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('matched_query_names', models.JSONField(blank=True, default=list)),
                ('subject_name', models.CharField(blank=True, max_length=64)),
                ('subject_scope', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_tls_service_profile_findings', to='assessments.assessmentrun')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssl_tls_service_profile_findings', to='assessments.control')),
                ('ssl_tls_service_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.ssltlsserviceprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SslTlsServiceProfileFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_tls_service_profile_finding_links', to='assessments.controlquery')),
                ('ssl_tls_service_profile_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.ssltlsserviceprofilefinding')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='ssltlsserviceprofilefinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='ssl_tls_service_profile_findings', through='assessments.SslTlsServiceProfileFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.AddConstraint(
            model_name='certificateprofilefindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('certificate_profile_finding', 'control_query'), name='unique_cp_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='certificateprofilefinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_65d961_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateprofilefinding',
            index=models.Index(fields=['certificate_profile'], name='assessments_certifi_f8dc18_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateprofilefinding',
            index=models.Index(fields=['status'], name='assessments_status_563d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateprofilefinding',
            index=models.Index(fields=['severity'], name='assessments_severit_6a321d_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificateprofilefinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'certificate_profile'), name='unique_cp_finding_per_run_control_object'),
        ),
        migrations.AddConstraint(
            model_name='ssltlsserviceprofilefindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('ssl_tls_service_profile_finding', 'control_query'), name='unique_stsp_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='ssltlsserviceprofilefinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_b7ca64_idx'),
        ),
        migrations.AddIndex(
            model_name='ssltlsserviceprofilefinding',
            index=models.Index(fields=['ssl_tls_service_profile'], name='assessments_ssl_tls_e67824_idx'),
        ),
        migrations.AddIndex(
            model_name='ssltlsserviceprofilefinding',
            index=models.Index(fields=['status'], name='assessments_status_f3f5bb_idx'),
        ),
        migrations.AddIndex(
            model_name='ssltlsserviceprofilefinding',
            index=models.Index(fields=['severity'], name='assessments_severit_8eddb1_idx'),
        ),
        migrations.AddConstraint(
            model_name='ssltlsserviceprofilefinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'ssl_tls_service_profile'), name='unique_stsp_finding_per_run_control_object'),
        ),
    ]
