# Generated by Django 6.0.8 on 2026-09-03 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_alter_control_control_type_certificateprofilefinding_and_more'),
        ('integrations', '0036_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_type',
            field=models.CharField(choices=[('security_rule', 'Security Rule'), ('config', 'Configuration'), ('device_configuration', 'Device Configuration'), ('management_interface', 'Management Interface'), ('interface_management_profile', 'Interface Management Profile'), ('ssl_tls_service_profile', 'SSL/TLS Service Profile'), ('certificate_profile', 'Certificate Profile'), ('certificate', 'Certificate')], default='security_rule', max_length=32),
        ),
        migrations.CreateModel(
            name='CertificateFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('matched_query_names', models.JSONField(blank=True, default=list)),
                ('subject_name', models.CharField(blank=True, max_length=64)),
                ('subject_scope', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_findings', to='assessments.assessmentrun')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.certificate')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_findings', to='assessments.control')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.certificatefinding')),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_finding_links', to='assessments.controlquery')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='certificatefinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='certificate_findings', through='assessments.CertificateFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.AddConstraint(
            model_name='certificatefindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('certificate_finding', 'control_query'), name='unique_cert_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='certificatefinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_71fb1d_idx'),
        ),
        migrations.AddIndex(
            model_name='certificatefinding',
            index=models.Index(fields=['certificate'], name='assessments_certifi_dd53ee_idx'),
        ),
        migrations.AddIndex(
            model_name='certificatefinding',
            index=models.Index(fields=['status'], name='assessments_status_4305bf_idx'),
        ),
        migrations.AddIndex(
            model_name='certificatefinding',
            index=models.Index(fields=['severity'], name='assessments_severit_bc0490_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificatefinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'certificate'), name='unique_cert_finding_per_run_control_object'),
        ),
    ]
