# Generated by Django 6.0.8 on 2026-09-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_alter_control_control_type_certificatefinding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='severity_scale',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
