# Generated by Django 6.0.8 on 2026-09-04 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_control_severity_scale'),
        ('integrations', '0039_authentication_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_type',
            field=models.CharField(choices=[('security_rule', 'Security Rule'), ('config', 'Configuration'), ('device_configuration', 'Device Configuration'), ('management_interface', 'Management Interface'), ('interface_management_profile', 'Interface Management Profile'), ('ssl_tls_service_profile', 'SSL/TLS Service Profile'), ('certificate_profile', 'Certificate Profile'), ('certificate', 'Certificate'), ('authentication_profile', 'Authentication Profile')], default='security_rule', max_length=32),
        ),
        migrations.CreateModel(
            name='AuthenticationProfileFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_query_names', models.JSONField(blank=True, default=list)),
                ('subject_name', models.CharField(blank=True, max_length=64)),
                ('subject_scope', models.CharField(blank=True, max_length=16)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authentication_profile_findings', to='assessments.assessmentrun')),
                ('authentication_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.authenticationprofile')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authentication_profile_findings', to='assessments.control')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthenticationProfileFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authentication_profile_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.authenticationprofilefinding')),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authentication_profile_finding_links', to='assessments.controlquery')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='authenticationprofilefinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='authentication_profile_findings', through='assessments.AuthenticationProfileFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.AddConstraint(
            model_name='authenticationprofilefindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('authentication_profile_finding', 'control_query'), name='unique_ap_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='authenticationprofilefinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_265627_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationprofilefinding',
            index=models.Index(fields=['status'], name='assessments_status_61ff39_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationprofilefinding',
            index=models.Index(fields=['severity'], name='assessments_severit_698518_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationprofilefinding',
            index=models.Index(fields=['authentication_profile'], name='assessments_authent_6a5725_idx'),
        ),
        migrations.AddConstraint(
            model_name='authenticationprofilefinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'authentication_profile'), name='unique_ap_finding_per_run_control_object'),
        ),
    ]
