# Generated by Django 6.0.8 on 2026-09-05 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_authentication_profile_finding'),
        ('integrations', '0040_password_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_type',
            field=models.CharField(choices=[('security_rule', 'Security Rule'), ('config', 'Configuration'), ('device_configuration', 'Device Configuration'), ('management_interface', 'Management Interface'), ('interface_management_profile', 'Interface Management Profile'), ('ssl_tls_service_profile', 'SSL/TLS Service Profile'), ('certificate_profile', 'Certificate Profile'), ('certificate', 'Certificate'), ('authentication_profile', 'Authentication Profile'), ('password_profile', 'Password Profile')], default='security_rule', max_length=32),
        ),
        migrations.CreateModel(
            name='PasswordProfileFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_query_names', models.JSONField(blank=True, default=list)),
                ('subject_name', models.CharField(blank=True, max_length=64)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_profile_findings', to='assessments.assessmentrun')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='password_profile_findings', to='assessments.control')),
                ('password_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.passwordprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordProfileFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_profile_finding_links', to='assessments.controlquery')),
                ('password_profile_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.passwordprofilefinding')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='passwordprofilefinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='password_profile_findings', through='assessments.PasswordProfileFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.AddConstraint(
            model_name='passwordprofilefindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('password_profile_finding', 'control_query'), name='unique_pp_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='passwordprofilefinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_3b0bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordprofilefinding',
            index=models.Index(fields=['status'], name='assessments_status_569f40_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordprofilefinding',
            index=models.Index(fields=['severity'], name='assessments_severit_efccc1_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordprofilefinding',
            index=models.Index(fields=['password_profile'], name='assessments_passwor_1abbff_idx'),
        ),
        migrations.AddConstraint(
            model_name='passwordprofilefinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'password_profile'), name='unique_pp_finding_per_run_control_object'),
        ),
    ]
