# Generated by Django 6.0.5 on 2026-09-08 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_password_profile_finding'),
        ('integrations', '0042_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_type',
            field=models.CharField(choices=[('security_rule', 'Security Rule'), ('config', 'Configuration'), ('device_configuration', 'Device Configuration'), ('management_interface', 'Management Interface'), ('interface_management_profile', 'Interface Management Profile'), ('ssl_tls_service_profile', 'SSL/TLS Service Profile'), ('certificate_profile', 'Certificate Profile'), ('certificate', 'Certificate'), ('authentication_profile', 'Authentication Profile'), ('password_profile', 'Password Profile'), ('admin_user', 'Administrator')], default='security_rule', max_length=32),
        ),
        migrations.CreateModel(
            name='AdminUserFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_query_names', models.JSONField(blank=True, default=list)),
                ('subject_name', models.CharField(blank=True, max_length=64)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.adminuser')),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user_findings', to='assessments.assessmentrun')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_user_findings', to='assessments.control')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminUserFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.adminuserfinding')),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user_finding_links', to='assessments.controlquery')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='adminuserfinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='admin_user_findings', through='assessments.AdminUserFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.AddConstraint(
            model_name='adminuserfindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('admin_user_finding', 'control_query'), name='unique_au_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='adminuserfinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_0a643d_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuserfinding',
            index=models.Index(fields=['status'], name='assessments_status_49ad3d_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuserfinding',
            index=models.Index(fields=['severity'], name='assessments_severit_efc660_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuserfinding',
            index=models.Index(fields=['admin_user'], name='assessments_admin_u_598958_idx'),
        ),
        migrations.AddConstraint(
            model_name='adminuserfinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'admin_user'), name='unique_au_finding_per_run_control_object'),
        ),
    ]
