# Generated by Django 6.0.5 on 2026-09-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_alter_control_control_type_adminuserfinding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='measure_field',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
