# Generated by Django 6.0.5 on 2026-09-09 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_control_measure_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='measure_field',
        ),
        migrations.RemoveField(
            model_name='control',
            name='severity_scale',
        ),
    ]
