# Generated by Django 6.0.5 on 2026-09-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0014_alter_control_control_type_serverprofilefinding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverprofilefinding',
            name='subject_scope',
            field=models.CharField(blank=True, max_length=72),
        ),
    ]
