# Generated by Django 6.0.5 on 2026-09-10 15:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0015_serverprofilefinding_subject_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSearchState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('model_label', models.CharField(max_length=128)),
                ('query_text', models.TextField(blank=True)),
                ('canonical_query', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
