# Generated by Django 6.0.5 on 2026-09-10 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0016_configurationsearchstate'),
        ('integrations', '0048_passwordcomplexitypolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_type',
            field=models.CharField(choices=[('security_rule', 'Security Rule'), ('config', 'Configuration'), ('device_configuration', 'Device Configuration'), ('management_interface', 'Management Interface'), ('interface_management_profile', 'Interface Management Profile'), ('ssl_tls_service_profile', 'SSL/TLS Service Profile'), ('certificate_profile', 'Certificate Profile'), ('certificate', 'Certificate'), ('authentication_profile', 'Authentication Profile'), ('password_profile', 'Password Profile'), ('password_complexity', 'Minimum Password Complexity'), ('admin_user', 'Administrator'), ('server_profile', 'AAA Server Profile')], default='security_rule', max_length=32),
        ),
        migrations.CreateModel(
            name='PasswordComplexityFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_query_names', models.JSONField(blank=True, default=list)),
                ('subject_name', models.CharField(blank=True, max_length=64)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_complexity_findings', to='assessments.assessmentrun')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='password_complexity_findings', to='assessments.control')),
                ('password_complexity_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.passwordcomplexitypolicy')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordComplexityFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_complexity_finding_links', to='assessments.controlquery')),
                ('password_complexity_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.passwordcomplexityfinding')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='passwordcomplexityfinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='password_complexity_findings', through='assessments.PasswordComplexityFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.AddConstraint(
            model_name='passwordcomplexityfindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('password_complexity_finding', 'control_query'), name='unique_pc_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='passwordcomplexityfinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_4e5813_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordcomplexityfinding',
            index=models.Index(fields=['status'], name='assessments_status_99fadc_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordcomplexityfinding',
            index=models.Index(fields=['severity'], name='assessments_severit_39aa3a_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordcomplexityfinding',
            index=models.Index(fields=['password_complexity_policy'], name='assessments_passwor_38eeff_idx'),
        ),
        migrations.AddConstraint(
            model_name='passwordcomplexityfinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'password_complexity_policy'), name='unique_pc_finding_per_run_control_object'),
        ),
    ]
