# Generated by Django 6.0.5 on 2026-09-10 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0017_alter_control_control_type_passwordcomplexityfinding_and_more'),
        ('integrations', '0049_authenticationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_type',
            field=models.CharField(choices=[('security_rule', 'Security Rule'), ('config', 'Configuration'), ('device_configuration', 'Device Configuration'), ('management_interface', 'Management Interface'), ('interface_management_profile', 'Interface Management Profile'), ('ssl_tls_service_profile', 'SSL/TLS Service Profile'), ('certificate_profile', 'Certificate Profile'), ('certificate', 'Certificate'), ('authentication_profile', 'Authentication Profile'), ('password_profile', 'Password Profile'), ('password_complexity', 'Minimum Password Complexity'), ('authentication_settings', 'Authentication Settings'), ('admin_user', 'Administrator'), ('server_profile', 'AAA Server Profile')], default='security_rule', max_length=32),
        ),
        migrations.CreateModel(
            name='AuthenticationSettingsFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_query_names', models.JSONField(blank=True, default=list)),
                ('subject_name', models.CharField(blank=True, max_length=64)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authentication_settings_findings', to='assessments.assessmentrun')),
                ('authentication_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.authenticationsettings')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authentication_settings_findings', to='assessments.control')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthenticationSettingsFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authentication_settings_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.authenticationsettingsfinding')),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authentication_settings_finding_links', to='assessments.controlquery')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='authenticationsettingsfinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='authentication_settings_findings', through='assessments.AuthenticationSettingsFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.AddConstraint(
            model_name='authenticationsettingsfindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('authentication_settings_finding', 'control_query'), name='unique_as_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='authenticationsettingsfinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_58b00b_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationsettingsfinding',
            index=models.Index(fields=['status'], name='assessments_status_24d18b_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationsettingsfinding',
            index=models.Index(fields=['severity'], name='assessments_severit_ebdef9_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationsettingsfinding',
            index=models.Index(fields=['authentication_settings'], name='assessments_authent_dab8f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='authenticationsettingsfinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'authentication_settings'), name='unique_as_finding_per_run_control_object'),
        ),
    ]
