# Generated by Django 6.0.5 on 2026-09-10 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0018_alter_control_control_type_and_more'),
        ('integrations', '0050_loginbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_type',
            field=models.CharField(choices=[('security_rule', 'Security Rule'), ('config', 'Configuration'), ('device_configuration', 'Device Configuration'), ('management_interface', 'Management Interface'), ('interface_management_profile', 'Interface Management Profile'), ('ssl_tls_service_profile', 'SSL/TLS Service Profile'), ('certificate_profile', 'Certificate Profile'), ('certificate', 'Certificate'), ('authentication_profile', 'Authentication Profile'), ('password_profile', 'Password Profile'), ('password_complexity', 'Minimum Password Complexity'), ('authentication_settings', 'Authentication Settings'), ('login_banner', 'Login Banner'), ('admin_user', 'Administrator'), ('server_profile', 'AAA Server Profile')], default='security_rule', max_length=32),
        ),
        migrations.CreateModel(
            name='LoginBannerFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_query_names', models.JSONField(blank=True, default=list)),
                ('subject_name', models.CharField(blank=True, max_length=64)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_banner_findings', to='assessments.assessmentrun')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='login_banner_findings', to='assessments.control')),
                ('login_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.loginbanner')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoginBannerFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_banner_finding_links', to='assessments.controlquery')),
                ('login_banner_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.loginbannerfinding')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='loginbannerfinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='login_banner_findings', through='assessments.LoginBannerFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.AddConstraint(
            model_name='loginbannerfindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('login_banner_finding', 'control_query'), name='unique_lb_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='loginbannerfinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_ba1c4b_idx'),
        ),
        migrations.AddIndex(
            model_name='loginbannerfinding',
            index=models.Index(fields=['status'], name='assessments_status_38ff68_idx'),
        ),
        migrations.AddIndex(
            model_name='loginbannerfinding',
            index=models.Index(fields=['severity'], name='assessments_severit_a56b93_idx'),
        ),
        migrations.AddIndex(
            model_name='loginbannerfinding',
            index=models.Index(fields=['login_banner'], name='assessments_login_b_0d2b9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='loginbannerfinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'login_banner'), name='unique_lb_finding_per_run_control_object'),
        ),
    ]
