# Generated by Django 6.0.5 on 2026-09-10 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0019_alter_control_control_type_loginbannerfinding_and_more'),
        ('integrations', '0051_loggingsettings_masterkey_updateserversettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_type',
            field=models.CharField(choices=[('security_rule', 'Security Rule'), ('config', 'Configuration'), ('device_configuration', 'Device Configuration'), ('management_interface', 'Management Interface'), ('interface_management_profile', 'Interface Management Profile'), ('ssl_tls_service_profile', 'SSL/TLS Service Profile'), ('certificate_profile', 'Certificate Profile'), ('certificate', 'Certificate'), ('authentication_profile', 'Authentication Profile'), ('password_profile', 'Password Profile'), ('password_complexity', 'Minimum Password Complexity'), ('authentication_settings', 'Authentication Settings'), ('login_banner', 'Login Banner'), ('master_key', 'Master Key'), ('update_server', 'Update Server Settings'), ('logging_settings', 'Logging and Reporting Settings'), ('admin_user', 'Administrator'), ('server_profile', 'AAA Server Profile')], default='security_rule', max_length=32),
        ),
        migrations.CreateModel(
            name='LoggingSettingsFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_query_names', models.JSONField(blank=True, default=list)),
                ('subject_name', models.CharField(blank=True, max_length=64)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logging_settings_findings', to='assessments.assessmentrun')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logging_settings_findings', to='assessments.control')),
                ('logging_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.loggingsettings')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoggingSettingsFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logging_settings_finding_links', to='assessments.controlquery')),
                ('logging_settings_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.loggingsettingsfinding')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='loggingsettingsfinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='logging_settings_findings', through='assessments.LoggingSettingsFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.CreateModel(
            name='MasterKeyFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_query_names', models.JSONField(blank=True, default=list)),
                ('subject_name', models.CharField(blank=True, max_length=64)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_key_findings', to='assessments.assessmentrun')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_key_findings', to='assessments.control')),
                ('master_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.masterkey')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterKeyFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_key_finding_links', to='assessments.controlquery')),
                ('master_key_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.masterkeyfinding')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='masterkeyfinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='master_key_findings', through='assessments.MasterKeyFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.CreateModel(
            name='UpdateServerSettingsFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_query_names', models.JSONField(blank=True, default=list)),
                ('subject_name', models.CharField(blank=True, max_length=64)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_server_settings_findings', to='assessments.assessmentrun')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='update_server_settings_findings', to='assessments.control')),
                ('update_server_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.updateserversettings')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpdateServerSettingsFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_server_settings_finding_links', to='assessments.controlquery')),
                ('update_server_settings_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.updateserversettingsfinding')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='updateserversettingsfinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='update_server_settings_findings', through='assessments.UpdateServerSettingsFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.AddConstraint(
            model_name='loggingsettingsfindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('logging_settings_finding', 'control_query'), name='unique_ls_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='loggingsettingsfinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_ee6a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='loggingsettingsfinding',
            index=models.Index(fields=['status'], name='assessments_status_3f4f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='loggingsettingsfinding',
            index=models.Index(fields=['severity'], name='assessments_severit_7ba257_idx'),
        ),
        migrations.AddIndex(
            model_name='loggingsettingsfinding',
            index=models.Index(fields=['logging_settings'], name='assessments_logging_7e41cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='loggingsettingsfinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'logging_settings'), name='unique_ls_finding_per_run_control_object'),
        ),
        migrations.AddConstraint(
            model_name='masterkeyfindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('master_key_finding', 'control_query'), name='unique_mk_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='masterkeyfinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_9e0ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='masterkeyfinding',
            index=models.Index(fields=['status'], name='assessments_status_6a414a_idx'),
        ),
        migrations.AddIndex(
            model_name='masterkeyfinding',
            index=models.Index(fields=['severity'], name='assessments_severit_8f3199_idx'),
        ),
        migrations.AddIndex(
            model_name='masterkeyfinding',
            index=models.Index(fields=['master_key'], name='assessments_master__a6e79d_idx'),
        ),
        migrations.AddConstraint(
            model_name='masterkeyfinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'master_key'), name='unique_mk_finding_per_run_control_object'),
        ),
        migrations.AddConstraint(
            model_name='updateserversettingsfindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('update_server_settings_finding', 'control_query'), name='unique_uss_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='updateserversettingsfinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_215f37_idx'),
        ),
        migrations.AddIndex(
            model_name='updateserversettingsfinding',
            index=models.Index(fields=['status'], name='assessments_status_098030_idx'),
        ),
        migrations.AddIndex(
            model_name='updateserversettingsfinding',
            index=models.Index(fields=['severity'], name='assessments_severit_120f11_idx'),
        ),
        migrations.AddIndex(
            model_name='updateserversettingsfinding',
            index=models.Index(fields=['update_server_settings'], name='assessments_update__8f930f_idx'),
        ),
        migrations.AddConstraint(
            model_name='updateserversettingsfinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'update_server_settings'), name='unique_uss_finding_per_run_control_object'),
        ),
    ]
