# Generated by Django 6.0.5 on 2026-09-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0021_alter_control_control_type_managementtlsfinding_and_more'),
    ]

    # DeviceConfigurationFinding holds a foreign key to integrations.DeviceConfigurationProfile,
    # so its table has to go before the integrations migration that deletes the profile table.
    # Integrations is a library and cannot depend on this app, so the ordering is declared here.
    run_before = [
        ("integrations", "0053_delete_deviceconfigurationprofile"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deviceconfigurationfinding',
            name='assessments_assessm_994852_idx',
        ),
        migrations.RemoveIndex(
            model_name='deviceconfigurationfinding',
            name='assessments_device__4b9fb8_idx',
        ),
        migrations.RemoveIndex(
            model_name='deviceconfigurationfinding',
            name='assessments_status_d0d1bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='deviceconfigurationfinding',
            name='assessments_severit_affca0_idx',
        ),
        migrations.RemoveConstraint(
            model_name='deviceconfigurationfinding',
            name='unique_device_configuration_finding_per_run_control_profile',
        ),
        migrations.RemoveConstraint(
            model_name='deviceconfigurationfindingcontrolquery',
            name='unique_device_configuration_finding_control_query_link',
        ),
        migrations.AlterField(
            model_name='control',
            name='control_type',
            field=models.CharField(choices=[('security_rule', 'Security Rule'), ('config', 'Configuration'), ('management_interface', 'Management Interface'), ('interface_management_profile', 'Interface Management Profile'), ('ssl_tls_service_profile', 'SSL/TLS Service Profile'), ('certificate_profile', 'Certificate Profile'), ('certificate', 'Certificate'), ('authentication_profile', 'Authentication Profile'), ('password_profile', 'Password Profile'), ('password_complexity', 'Minimum Password Complexity'), ('authentication_settings', 'Authentication Settings'), ('login_banner', 'Login Banner'), ('master_key', 'Master Key'), ('update_server', 'Update Server Settings'), ('logging_settings', 'Logging and Reporting Settings'), ('management_tls', 'Management TLS'), ('admin_user', 'Administrator'), ('server_profile', 'AAA Server Profile')], default='security_rule', max_length=32),
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationfindingcontrolquery',
            name='control_query',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationfindingcontrolquery',
            name='device_configuration_finding',
        ),
        migrations.DeleteModel(
            name='DeviceConfigurationFinding',
        ),
        migrations.DeleteModel(
            name='DeviceConfigurationFindingControlQuery',
        ),
    ]
