# Generated by Django 6.0.5 on 2026-09-11 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0022_remove_deviceconfigurationfinding_assessments_assessm_994852_idx_and_more'),
        ('integrations', '0054_authenticationsequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_type',
            field=models.CharField(choices=[('security_rule', 'Security Rule'), ('config', 'Configuration'), ('management_interface', 'Management Interface'), ('interface_management_profile', 'Interface Management Profile'), ('ssl_tls_service_profile', 'SSL/TLS Service Profile'), ('certificate_profile', 'Certificate Profile'), ('certificate', 'Certificate'), ('authentication_profile', 'Authentication Profile'), ('authentication_sequence', 'Authentication Sequence'), ('password_profile', 'Password Profile'), ('password_complexity', 'Minimum Password Complexity'), ('authentication_settings', 'Authentication Settings'), ('login_banner', 'Login Banner'), ('master_key', 'Master Key'), ('update_server', 'Update Server Settings'), ('logging_settings', 'Logging and Reporting Settings'), ('management_tls', 'Management TLS'), ('admin_user', 'Administrator'), ('server_profile', 'AAA Server Profile')], default='security_rule', max_length=32),
        ),
        migrations.CreateModel(
            name='AuthenticationSequenceFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_query_names', models.JSONField(blank=True, default=list)),
                ('subject_name', models.CharField(blank=True, max_length=64)),
                ('subject_scope', models.CharField(blank=True, max_length=16)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authentication_sequence_findings', to='assessments.assessmentrun')),
                ('authentication_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.authenticationsequence')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authentication_sequence_findings', to='assessments.control')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthenticationSequenceFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authentication_sequence_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.authenticationsequencefinding')),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authentication_sequence_finding_links', to='assessments.controlquery')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='authenticationsequencefinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='authentication_sequence_findings', through='assessments.AuthenticationSequenceFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.AddConstraint(
            model_name='authenticationsequencefindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('authentication_sequence_finding', 'control_query'), name='unique_aseq_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='authenticationsequencefinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_932f66_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationsequencefinding',
            index=models.Index(fields=['status'], name='assessments_status_2c9c82_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationsequencefinding',
            index=models.Index(fields=['severity'], name='assessments_severit_75cf45_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationsequencefinding',
            index=models.Index(fields=['authentication_sequence'], name='assessments_authent_6494f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='authenticationsequencefinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'authentication_sequence'), name='unique_aseq_finding_per_run_control_object'),
        ),
    ]
