# Generated by Django 6.0.5 on 2026-09-11 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0023_authenticationsequencefinding'),
        ('integrations', '0055_managementsshsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_type',
            field=models.CharField(choices=[('security_rule', 'Security Rule'), ('config', 'Configuration'), ('management_interface', 'Management Interface'), ('interface_management_profile', 'Interface Management Profile'), ('ssl_tls_service_profile', 'SSL/TLS Service Profile'), ('certificate_profile', 'Certificate Profile'), ('certificate', 'Certificate'), ('authentication_profile', 'Authentication Profile'), ('authentication_sequence', 'Authentication Sequence'), ('password_profile', 'Password Profile'), ('password_complexity', 'Minimum Password Complexity'), ('authentication_settings', 'Authentication Settings'), ('login_banner', 'Login Banner'), ('master_key', 'Master Key'), ('update_server', 'Update Server Settings'), ('logging_settings', 'Logging and Reporting Settings'), ('management_tls', 'Management TLS'), ('management_ssh', 'Management SSH'), ('admin_user', 'Administrator'), ('server_profile', 'AAA Server Profile')], default='security_rule', max_length=32),
        ),
        migrations.CreateModel(
            name='ManagementSshFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_query_names', models.JSONField(blank=True, default=list)),
                ('subject_name', models.CharField(blank=True, max_length=64)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_ssh_findings', to='assessments.assessmentrun')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='management_ssh_findings', to='assessments.control')),
                ('management_ssh_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.managementsshsettings')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManagementSshFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_ssh_finding_links', to='assessments.controlquery')),
                ('management_ssh_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.managementsshfinding')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='managementsshfinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='management_ssh_findings', through='assessments.ManagementSshFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.AddConstraint(
            model_name='managementsshfindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('management_ssh_finding', 'control_query'), name='unique_mssh_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='managementsshfinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_b64318_idx'),
        ),
        migrations.AddIndex(
            model_name='managementsshfinding',
            index=models.Index(fields=['status'], name='assessments_status_1f1c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='managementsshfinding',
            index=models.Index(fields=['severity'], name='assessments_severit_ade733_idx'),
        ),
        migrations.AddIndex(
            model_name='managementsshfinding',
            index=models.Index(fields=['management_ssh_settings'], name='assessments_managem_1914b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='managementsshfinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'management_ssh_settings'), name='unique_mssh_finding_per_run_control_object'),
        ),
    ]
