# Generated by Django 6.0.5 on 2026-09-14 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0025_alter_control_control_type_securityprofilefinding_and_more'),
        ('integrations', '0059_ssh_below_preferred_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_type',
            field=models.CharField(choices=[('security_rule', 'Security Rule'), ('config', 'Configuration'), ('management_interface', 'Management Interface'), ('interface_management_profile', 'Interface Management Profile'), ('ssl_tls_service_profile', 'SSL/TLS Service Profile'), ('certificate_profile', 'Certificate Profile'), ('certificate', 'Certificate'), ('authentication_profile', 'Authentication Profile'), ('authentication_sequence', 'Authentication Sequence'), ('password_profile', 'Password Profile'), ('security_profile', 'Security Profile'), ('password_complexity', 'Minimum Password Complexity'), ('authentication_settings', 'Authentication Settings'), ('login_banner', 'Login Banner'), ('master_key', 'Master Key'), ('update_server', 'Update Server Settings'), ('logging_settings', 'Logging and Reporting Settings'), ('management_tls', 'Management TLS'), ('management_ssh', 'Management SSH'), ('admin_user', 'Administrator'), ('server_profile', 'AAA Server Profile'), ('ntp_settings', 'NTP'), ('snmp_settings', 'SNMP'), ('system_identity', 'System Identity')], default='security_rule', max_length=32),
        ),
        migrations.CreateModel(
            name='NtpSettingsFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_query_names', models.JSONField(blank=True, default=list)),
                ('subject_name', models.CharField(blank=True, max_length=64)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ntp_settings_findings', to='assessments.assessmentrun')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ntp_settings_findings', to='assessments.control')),
                ('ntp_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.ntpsettings')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NtpSettingsFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ntp_settings_finding_links', to='assessments.controlquery')),
                ('ntp_settings_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.ntpsettingsfinding')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ntpsettingsfinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='ntp_settings_findings', through='assessments.NtpSettingsFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.CreateModel(
            name='SnmpSettingsFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_query_names', models.JSONField(blank=True, default=list)),
                ('subject_name', models.CharField(blank=True, max_length=64)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_settings_findings', to='assessments.assessmentrun')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snmp_settings_findings', to='assessments.control')),
                ('snmp_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.snmpsettings')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SnmpSettingsFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_settings_finding_links', to='assessments.controlquery')),
                ('snmp_settings_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.snmpsettingsfinding')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='snmpsettingsfinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='snmp_settings_findings', through='assessments.SnmpSettingsFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.CreateModel(
            name='SystemIdentityFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_query_names', models.JSONField(blank=True, default=list)),
                ('subject_name', models.CharField(blank=True, max_length=64)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_identity_findings', to='assessments.assessmentrun')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='system_identity_findings', to='assessments.control')),
                ('system_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.systemidentity')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemIdentityFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_identity_finding_links', to='assessments.controlquery')),
                ('system_identity_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.systemidentityfinding')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='systemidentityfinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='system_identity_findings', through='assessments.SystemIdentityFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.AddConstraint(
            model_name='ntpsettingsfindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('ntp_settings_finding', 'control_query'), name='unique_ntp_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='ntpsettingsfinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_f7e1a0_idx'),
        ),
        migrations.AddIndex(
            model_name='ntpsettingsfinding',
            index=models.Index(fields=['status'], name='assessments_status_8e672b_idx'),
        ),
        migrations.AddIndex(
            model_name='ntpsettingsfinding',
            index=models.Index(fields=['severity'], name='assessments_severit_971042_idx'),
        ),
        migrations.AddIndex(
            model_name='ntpsettingsfinding',
            index=models.Index(fields=['ntp_settings'], name='assessments_ntp_set_560f8e_idx'),
        ),
        migrations.AddConstraint(
            model_name='ntpsettingsfinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'ntp_settings'), name='unique_ntp_finding_per_run_control_object'),
        ),
        migrations.AddConstraint(
            model_name='snmpsettingsfindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('snmp_settings_finding', 'control_query'), name='unique_snmp_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='snmpsettingsfinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_4034c7_idx'),
        ),
        migrations.AddIndex(
            model_name='snmpsettingsfinding',
            index=models.Index(fields=['status'], name='assessments_status_a30a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='snmpsettingsfinding',
            index=models.Index(fields=['severity'], name='assessments_severit_b4445a_idx'),
        ),
        migrations.AddIndex(
            model_name='snmpsettingsfinding',
            index=models.Index(fields=['snmp_settings'], name='assessments_snmp_se_669b4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='snmpsettingsfinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'snmp_settings'), name='unique_snmp_finding_per_run_control_object'),
        ),
        migrations.AddConstraint(
            model_name='systemidentityfindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('system_identity_finding', 'control_query'), name='unique_sysid_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='systemidentityfinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_99c5d4_idx'),
        ),
        migrations.AddIndex(
            model_name='systemidentityfinding',
            index=models.Index(fields=['status'], name='assessments_status_37e547_idx'),
        ),
        migrations.AddIndex(
            model_name='systemidentityfinding',
            index=models.Index(fields=['severity'], name='assessments_severit_3fb331_idx'),
        ),
        migrations.AddIndex(
            model_name='systemidentityfinding',
            index=models.Index(fields=['system_identity'], name='assessments_system__f69c4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='systemidentityfinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'system_identity'), name='unique_sysid_finding_per_run_control_object'),
        ),
    ]
