# Generated by Django 6.0.5 on 2026-09-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0027_finding_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulefinding',
            name='subject_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rulefinding',
            name='subject_scope',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
