# Generated by Django 6.0.5 on 2026-09-25 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0028_rulefinding_subject_name_rulefinding_subject_scope'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecurityRuleSearchState',
        ),
    ]
