# Generated by Django 6.0.5 on 2026-10-02 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0029_drop_security_rule_search_state'),
        ('integrations', '0066_address_object_resolved_content_completeness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_type',
            field=models.CharField(choices=[('security_rule', 'Security Rule'), ('coverage', 'Coverage'), ('config', 'Configuration'), ('management_interface', 'Management Interface'), ('interface_management_profile', 'Interface Management Profile'), ('ssl_tls_service_profile', 'SSL/TLS Service Profile'), ('certificate_profile', 'Certificate Profile'), ('certificate', 'Certificate'), ('authentication_profile', 'Authentication Profile'), ('authentication_sequence', 'Authentication Sequence'), ('password_profile', 'Password Profile'), ('security_profile', 'Security Profile'), ('password_complexity', 'Minimum Password Complexity'), ('authentication_settings', 'Authentication Settings'), ('login_banner', 'Login Banner'), ('master_key', 'Master Key'), ('update_server', 'Update Server Settings'), ('logging_settings', 'Logging and Reporting Settings'), ('management_tls', 'Management TLS'), ('management_ssh', 'Management SSH'), ('admin_user', 'Administrator'), ('server_profile', 'AAA Server Profile'), ('ntp_settings', 'NTP'), ('snmp_settings', 'SNMP'), ('system_identity', 'System Identity')], default='security_rule', max_length=32),
        ),
        migrations.CreateModel(
            name='CoverageFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.PositiveIntegerField(editable=False)),
                ('matched_query_names', models.JSONField(blank=True, default=list)),
                ('subject_name', models.CharField(blank=True, max_length=64)),
                ('address_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_findings', to='integrations.addressobject')),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_findings', to='assessments.assessmentrun')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coverage_findings', to='assessments.control')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoverageFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_finding_links', to='assessments.controlquery')),
                ('coverage_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.coveragefinding')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='coveragefinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='coverage_findings', through='assessments.CoverageFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.AddIndex(
            model_name='coveragefinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_c2a5af_idx'),
        ),
        migrations.AddIndex(
            model_name='coveragefinding',
            index=models.Index(fields=['status'], name='assessments_status_cc214c_idx'),
        ),
        migrations.AddIndex(
            model_name='coveragefinding',
            index=models.Index(fields=['severity'], name='assessments_severit_19384d_idx'),
        ),
        migrations.AddIndex(
            model_name='coveragefinding',
            index=models.Index(fields=['address_object'], name='assessments_address_e90c0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='coveragefinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'reference_number'), name='assessments_coveragefinding_unique_reference_per_run'),
        ),
        migrations.AddConstraint(
            model_name='coveragefinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'address_object'), name='unique_coverage_finding_per_run_control_object'),
        ),
    ]
