# Generated by Django 6.0.5 on 2026-10-05 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0030_coverage_findings'),
        ('integrations', '0067_security_rule_address_breadth'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuserfinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='authenticationprofilefinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='authenticationsequencefinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='authenticationsettingsfinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='certificatefinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='certificateprofilefinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='coveragefinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='interfacemanagementprofilefinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='loggingsettingsfinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='loginbannerfinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='managementinterfacefinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='managementsshfinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='managementtlsfinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='masterkeyfinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='ntpsettingsfinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='passwordcomplexityfinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='passwordprofilefinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='rulefinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='securityprofilefinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='serverprofilefinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='snmpsettingsfinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='ssltlsserviceprofilefinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='systemidentityfinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='updateserversettingsfinding',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot'),
        ),
    ]
