# Generated by Django 6.0.5 on 2026-10-09 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0031_adminuserfinding_snapshot_and_more'),
        ('integrations', '0079_wildfire_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_type',
            field=models.CharField(choices=[('security_rule', 'Security Rule'), ('coverage', 'Coverage'), ('config', 'Configuration'), ('management_interface', 'Management Interface'), ('interface_management_profile', 'Interface Management Profile'), ('ssl_tls_service_profile', 'SSL/TLS Service Profile'), ('certificate_profile', 'Certificate Profile'), ('certificate', 'Certificate'), ('authentication_profile', 'Authentication Profile'), ('authentication_sequence', 'Authentication Sequence'), ('password_profile', 'Password Profile'), ('security_profile', 'Security Profile'), ('password_complexity', 'Minimum Password Complexity'), ('authentication_settings', 'Authentication Settings'), ('login_banner', 'Login Banner'), ('master_key', 'Master Key'), ('update_server', 'Update Server Settings'), ('logging_settings', 'Logging and Reporting Settings'), ('wildfire_settings', 'WildFire Settings'), ('management_tls', 'Management TLS'), ('management_ssh', 'Management SSH'), ('admin_user', 'Administrator'), ('server_profile', 'AAA Server Profile'), ('ntp_settings', 'NTP'), ('snmp_settings', 'SNMP'), ('system_identity', 'System Identity')], default='security_rule', max_length=32),
        ),
        migrations.CreateModel(
            name='WildfireSettingsFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('informational', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.PositiveIntegerField(editable=False)),
                ('matched_query_names', models.JSONField(blank=True, default=list)),
                ('subject_name', models.CharField(blank=True, max_length=64)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wildfire_settings_findings', to='assessments.assessmentrun')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wildfire_settings_findings', to='assessments.control')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.snapshot')),
                ('wildfire_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.wildfiresettings')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WildfireSettingsFindingControlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wildfire_settings_finding_links', to='assessments.controlquery')),
                ('wildfire_settings_finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_links', to='assessments.wildfiresettingsfinding')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='wildfiresettingsfinding',
            name='control_queries',
            field=models.ManyToManyField(blank=True, related_name='wildfire_settings_findings', through='assessments.WildfireSettingsFindingControlQuery', to='assessments.controlquery'),
        ),
        migrations.AddConstraint(
            model_name='wildfiresettingsfindingcontrolquery',
            constraint=models.UniqueConstraint(fields=('wildfire_settings_finding', 'control_query'), name='unique_wfs_finding_control_query_link'),
        ),
        migrations.AddIndex(
            model_name='wildfiresettingsfinding',
            index=models.Index(fields=['assessment_run', 'control'], name='assessments_assessm_3a5abb_idx'),
        ),
        migrations.AddIndex(
            model_name='wildfiresettingsfinding',
            index=models.Index(fields=['status'], name='assessments_status_9be29f_idx'),
        ),
        migrations.AddIndex(
            model_name='wildfiresettingsfinding',
            index=models.Index(fields=['severity'], name='assessments_severit_a076db_idx'),
        ),
        migrations.AddIndex(
            model_name='wildfiresettingsfinding',
            index=models.Index(fields=['wildfire_settings'], name='assessments_wildfir_f41d33_idx'),
        ),
        migrations.AddConstraint(
            model_name='wildfiresettingsfinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'reference_number'), name='assessments_wildfiresettingsfinding_unique_reference_per_run'),
        ),
        migrations.AddConstraint(
            model_name='wildfiresettingsfinding',
            constraint=models.UniqueConstraint(fields=('assessment_run', 'control', 'wildfire_settings'), name='unique_wfs_finding_per_run_control_object'),
        ),
    ]
